In [15]:
# Import modules
import pandas as pd
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

In [16]:
## Read in the Data

# Create file path
gdp_file = Path('../Resources/GDP_Data_MPD.csv')

# Read in Data
#df = pd.read_csv(file, encoding="UTF-8", low_memory=False)
gdp_file_df = pd.read_csv(gdp_file)
display(gdp_file_df)

,countrycode,country,region,year,gdppc,pop
0,AFG,Afghanistan,South and South East Asia,1,NaN,NaN
1,AFG,Afghanistan,South and South East Asia,730,NaN,NaN
2,AFG,Afghanistan,South and South East Asia,1000,NaN,NaN
3,AFG,Afghanistan,South and South East Asia,1090,NaN,NaN
4,AFG,Afghanistan,South and South East Asia,1150,NaN,NaN
...,...,...,...,...,...,...
131139,ZWE,Zimbabwe,Sub Saharan Africa,2018,1900.0,14097.0
131140,ZWE,Zimbabwe,Sub Saharan Africa,2019,1753.0,14345.0
131141,ZWE,Zimbabwe,Sub Saharan Africa,2020,1586.0,14615.0
131142,ZWE,Zimbabwe,Sub Saharan Africa,2021,1687.0,14900.0
131143,ZWE,Zimbabwe,Sub Saharan Africa,2022,1704.0,15205.0

In [17]:
# Clean the data

# Strip whitespace from column titles
gdp_file_df.columns = gdp_file_df.columns.str.strip()
# Rename useful columns as needed 
renamed_df = gdp_file_df.rename(columns={"country":"Country", 
                                                "year":"Year",
                                                "gdppc":"GDP per Capita",
                                                "region":"Region"
                                               })
renamed_df

,countrycode,Country,Region,Year,GDP per Capita,pop
0,AFG,Afghanistan,South and South East Asia,1,NaN,NaN
1,AFG,Afghanistan,South and South East Asia,730,NaN,NaN
2,AFG,Afghanistan,South and South East Asia,1000,NaN,NaN
3,AFG,Afghanistan,South and South East Asia,1090,NaN,NaN
4,AFG,Afghanistan,South and South East Asia,1150,NaN,NaN
...,...,...,...,...,...,...
131139,ZWE,Zimbabwe,Sub Saharan Africa,2018,1900.0,14097.0
131140,ZWE,Zimbabwe,Sub Saharan Africa,2019,1753.0,14345.0
131141,ZWE,Zimbabwe,Sub Saharan Africa,2020,1586.0,14615.0
131142,ZWE,Zimbabwe,Sub Saharan Africa,2021,1687.0,14900.0
131143,ZWE,Zimbabwe,Sub Saharan Africa,2022,1704.0,15205.0

In [18]:
# Manual mapping dictionary to match names of few countries with UN life Expectancy file
country_mapping = {
    "United States": "United States of America",
    "D.P.R. of Korea": "Dem. People's Republic of Korea",
    "D.R. of the Congo": "Democratic Republic of the Congo",
    "U.R. of Tanzania: Mainland": "United Republic of Tanzania",
    "Taiwan, Province of China": "China, Taiwan Province of China",
    "TFYR of Macedonia": "North Macedonia",
    "Turkey": "TÃ¼rkiye"
}
# Standardize country names in gdp file
renamed_df['Country'] = renamed_df['Country'].replace(country_mapping)
renamed_df

,countrycode,Country,Region,Year,GDP per Capita,pop
0,AFG,Afghanistan,South and South East Asia,1,NaN,NaN
1,AFG,Afghanistan,South and South East Asia,730,NaN,NaN
2,AFG,Afghanistan,South and South East Asia,1000,NaN,NaN
3,AFG,Afghanistan,South and South East Asia,1090,NaN,NaN
4,AFG,Afghanistan,South and South East Asia,1150,NaN,NaN
...,...,...,...,...,...,...
131139,ZWE,Zimbabwe,Sub Saharan Africa,2018,1900.0,14097.0
131140,ZWE,Zimbabwe,Sub Saharan Africa,2019,1753.0,14345.0
131141,ZWE,Zimbabwe,Sub Saharan Africa,2020,1586.0,14615.0
131142,ZWE,Zimbabwe,Sub Saharan Africa,2021,1687.0,14900.0
131143,ZWE,Zimbabwe,Sub Saharan Africa,2022,1704.0,15205.0

In [19]:
renamed_df.dtypes

countrycode        object
Country            object
Region             object
Year                int64
GDP per Capita    float64
pop               float64
dtype: object

In [20]:
# Specify the file path where you want to save the CSV file
csv_file_path = '../output/csv/final_gdp.csv'

# Write final_df to CSV
renamed_df.to_csv(csv_file_path, index=False)

print(f"DataFrame successfully written to {csv_file_path}")

DataFrame successfully written to ../output/csv/final_gdp.csv